[pytest]
# Автоматические флаги для любого запуска
addopts =
    -v
    -m "not broken"


markers =
    smoke: Критичный путь (Smoke-тесты)
    registration: Тесты регистрации
    negative: Негативные сценарии
    login: Тесты авторизации

testpaths = tests

